### ISSUE TITLE
Regarding the results of TCP

### ISSUE THREAD

**Issue by huyquangdao** [iwangjian/Plan4RecDial#2]
Hi authors

Thank you very much for your interesting paper and the published source code. 

Currently, we're trying to reproduce the reported results in the paper. However, the reproduced results are different with the reported ones. Specifically, we got the following logs after running and testing the TCP module.

Action ACC: 77.87%
Action Bi-ACC: 79.01%
Topic ACC: 35.45%
Topic Bi-ACC: 36.90%

Those results are much lower than your reported ones. I'm certain that I did nothing wrong since I strictly followed your instructions in this repo. Looking forward to your response.

**Comment by iwangjian** [comment]
Hi, thanks for raising this question. I'm sorry that I mixed some codes up during cleaning the project. I have fixed the issue and updated this repo. Please try the latest commit.
